config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#list'
  post '/tasks', to: 'tasks#create'
  get '/tasks/new', to: 'tasks#new', as: 'new'
  delete 'tasks/:id/delete', to: 'tasks#destroy', as: 'destroy'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch '/tasks/:id', to: 'tasks#update'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def list
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @tasks = Task.new
  end

  def create
    @tasks = Task.new(task_params)
    @tasks.save!
    redirect_to tasks_path
  end

  def edit
    @tasks = Task.find(params[:id])
  end

  def update
    @tasks = Task.find(params[:id])
    @tasks.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @tasks = Task.find(params[:id])
    @tasks.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/application.css" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="background">
  <nav align="center" class="pt-3 pb-3">
  <h1>🌱 My tasks 🌿</h1>
  </nav>
  <h2 class="pt-3" align="center">"Nothing inspires cleanliness more than an unexpected guest”</h2>
  <div class="p-5 main">
    <%= yield %>
  </div>
  </body>
  <hr>
</html>

app/views/tasks/edit.html.erb
<h2>Update a Task 🪸</h2>
<%= form_with(model:@tasks) do |form| %>
  <%= form.label :title %><br>
  <%= form.text_field :title %><br>
<br>
  <%= form.label :details %><br>
  <%= form.text_area :details %><br>
<br>
  <%= form.label :completed %><br>
  <%= form.check_box :completed %><br>
<br>
  <%= form.submit %>
<%end%>

<div class="pt-5">
<%= link_to "Go home", tasks_path, {class: "btn-orange "} %>
</div>

app/views/tasks/list.html.erb
<h2>To do</h2>
<br>
<ul id="list">
<% @tasks.each do | task | %>
  <li>
  <%= link_to task.title, task_path(task) %>
  </li>
  <% end %>
  </ul>
<br>

<%= link_to "Create a Task 💐", new_path, {class: "btn-red"} %>

app/views/tasks/new.html.erb
<h2>Create a Task 💐</h2>
<br>
<%= form_with(model:@tasks) do |form| %>
  <%= form.label :title %> <br>
  <%= form.text_field :title %><br>
<br>
  <%= form.label :details %><br>
  <%= form.text_area :details %><br>
<br>
  <%= form.label :completed %><br>
  <%= form.check_box :completed %><br>
<br>
  <%= form.submit %>
<%end%>
<div class="pt-5">
<%= link_to "Go home", tasks_path, {class: "btn-orange"} %>
</div>

app/views/tasks/show.html.erb
<p><strong>Title:</strong> <%= @tasks.title %></p>
<p><strong>Details:</strong> <%= @tasks.details %></p>
<p><strong>Completed?:</strong> <%= @tasks.completed %></p>

<div class="a pt-3">
<%= link_to "Go back", tasks_path, {class: "btn-orange"}%>
<%= link_to "Update a Task 🪸", edit_path, {class: "btn-blue"} %>
<%= link_to "Delete a Task 🗑", destroy_path(@tasks), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>